apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: main
  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - init

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value: "--count --max-complexity=10 --max-line-length=127 --statistics"
      runAfter:
        - clone
      taskSpec:
        params:
          - name: image
            type: string
            default: "python:3.9-slim"
          - name: args
            type: string
            default: ""
        workspaces:
          - name: source
        steps:
          - name: step-flake8
            image: $(params.image)
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              pip install --no-cache-dir flake8
              echo "Running flake8 with args: $(params.args)"
              flake8 . $(params.args)